# Generated by Django 4.0.3 on 2022-03-07 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characters', '0007_alter_character_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_image',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='character',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='character',
            name='stats',
            field=models.CharField(default='', max_length=300),
        ),
    ]
