# Generated by Django 4.0.3 on 2022-03-07 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_alter_character_character_image_and_more'),
        ('game', '0004_alter_game_description_alter_game_game_image_and_more'),
        ('comments', '0004_alter_comment_character_alter_comment_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='characters.character'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='game.game'),
        ),
    ]
