# Generated by Django 4.0.3 on 2022-03-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('game_image', models.CharField(default='', max_length=500)),
                ('stats', models.CharField(default='', max_length=300)),
                ('description', models.CharField(default='', max_length=500)),
                ('character', models.ManyToManyField(default='', related_name='game', to='characters.character')),
            ],
        ),
    ]
