# Generated by Django 4.0.3 on 2022-03-07 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='members',
            field=models.ManyToManyField(related_name='game', to=settings.AUTH_USER_MODEL),
        ),
    ]
