# Generated by Django 4.0.3 on 2022-03-07 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_alter_character_character_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='character',
            field=models.ManyToManyField(default='', related_name='game', to='characters.character'),
        ),
        migrations.AlterField(
            model_name='game',
            name='members',
            field=models.ManyToManyField(default='', related_name='game', to=settings.AUTH_USER_MODEL),
        ),
    ]
