# Generated by Django 4.0.3 on 2022-03-07 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_owner_alter_game_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='character',
        ),
        migrations.RemoveField(
            model_name='game',
            name='members',
        ),
        migrations.RemoveField(
            model_name='game',
            name='owner',
        ),
    ]
