# Generated by Django 4.0.3 on 2022-03-07 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_alter_character_character_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0006_remove_game_character_remove_game_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='character',
            field=models.ManyToManyField(default='', related_name='game', to='characters.character'),
        ),
        migrations.AddField(
            model_name='game',
            name='members',
            field=models.ManyToManyField(default='', related_name='games_joined', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='games_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
